name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v7
      - name: Build app
        run: ./build.sh
      - name: Upload app
        uses: actions/upload-artifact@v7
        with:
          name: Klarvaken.app
          path: build/Klarvaken.app.zip
