name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build app
        run: ./build.sh
      - name: Upload app
        uses: actions/upload-artifact@v4
        with:
          name: Stay_Awake.app
          path: build/Stay_Awake.app.zip
